DROP TABLE ACTIVITY IF EXISTS;
CREATE TABLE ACTIVITY (ID NUMBER(48) NOT NULL,COMPLETED NUMBER(1) NOT NULL,TITLE VARCHAR(255),PRIMARY KEY(ID));
CREATE SEQUENCE IF NOT EXISTS SEQ_ACTIVITY START WITH 1 INCREMENT BY 1;